### ISSUE TITLE
Still working fine in 2021 with 5.15.11-200.fc35.x86_64

### ISSUE THREAD

**Issue by adelton** [asymingt/rts5139#23]
Similar to https://github.com/asymingt/rts5139/issues/5, just a note that on Fedora 35 with kernel 5.15.11-200.fc35.x86_64, the steps and resulting module works for

```
# lsusb | grep Card
Bus 001 Device 002: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
```

and resolves the

```
mmc3: tuning execution failed: -22
mmc3: error -22 whilst initialising SD card
```

issue on UMAX VisionBook 13Wa Pro, a.k.a. Jumper EZbook 3 Pro.

Thank you for maintaining it.

**Comment by abrattic** [comment]
> Similar to #5, just a note that on Fedora 35 with kernel 5.15.11-200.fc35.x86_64, the steps and resulting module works for
> 
> ```
> # lsusb | grep Card
> Bus 001 Device 002: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
> ```
> 
> and resolves the
> 
> ```
> mmc3: tuning execution failed: -22
> mmc3: error -22 whilst initialising SD card
> ```
> 
> issue on UMAX VisionBook 13Wa Pro, a.k.a. Jumper EZbook 3 Pro.
> 
> Thank you for maintaining it.


Could you help me? It throws me an error when I try to build it on archlinux:

```make -C /lib/modules/5.16.0-arch1-1/build/ M=/tmp/rts5139 modules
make[1]: Entering directory '/usr/lib/modules/5.16.0-arch1-1/build'
  CC [M]  /tmp/rts5139/rts51x_scsi.o
/tmp/rts5139/rts51x_scsi.c: In function ‘queuecommand_lck’:
/tmp/rts5139/rts51x_scsi.c:2017:12: error: ‘struct scsi_cmnd’ has no member named ‘scsi_done’
 2017 |         srb->scsi_done = done;
      |            ^~
In file included from /tmp/rts5139/rts51x.h:44,
                 from /tmp/rts5139/rts51x_scsi.c:39:
/tmp/rts5139/rts51x_scsi.c: In function ‘queuecommand’:
/tmp/rts5139/rts51x_scsi.c:2024:15: error: too few arguments to function ‘queuecommand_lck’
 2024 | DEF_SCSI_QCMD(queuecommand)
      |               ^~~~~~~~~~~~
./include/scsi/scsi_host.h:514:22: note: in definition of macro ‘DEF_SCSI_QCMD’
  514 |                 rc = func_name##_lck(cmd);                              \
      |                      ^~~~~~~~~
/tmp/rts5139/rts51x_scsi.c:1997:5: note: declared here
 1997 | int queuecommand_lck(struct scsi_cmnd *srb, void (*done) (struct scsi_cmnd *))
      |     ^~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:287: /tmp/rts5139/rts51x_scsi.o] Error 1
make[1]: *** [Makefile:1846: /tmp/rts5139] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.16.0-arch1-1/build'
make: *** [Makefile:46: all] Error 2```
